name: Build and Release

on:
  push:
    branches: ["main"]

jobs:
  check-release:
    name: Check if the release already exists
    permissions:
      contents: read
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4

    - name: Get package version
      id: version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

    - name: Check if release exists
      id: check
      run: |
        if gh release view v${{ steps.version.outputs.version }}; then
          echo "Release v${{ steps.version.outputs.version }} already exists."
          echo "should_run=false" >> $GITHUB_OUTPUT
        else
          echo "Release v${{ steps.version.outputs.version }} does not exist."
        fi
  build:
    needs: check-release
    if: ${{ needs.check-release.outputs.should_run != 'false' }}
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build-group: linux-x64
          - os: macos-12
            build-group: darwin-x64+arm64
    name: Build ${{ matrix.build-group }}
    env:
      BUILD_GROUP: ${{ matrix.build-group }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install
        run: npm install --ignore-scripts
      - name: Prebuild
        run: npm run prebuild-$BUILD_GROUP
        shell: bash
      - name: Prepare artifact
        run: tar -zcvf $BUILD_GROUP.tar.gz prebuilds/
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_GROUP }}
          path: ${{ env.BUILD_GROUP }}.tar.gz
          retention-days: 1
  release:
    needs: build
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Get package version
        id: version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          name: v${{ steps.version.outputs.version }}
          tag: v${{ steps.version.outputs.version }}
          body: |
            This is an automated release built from the `main` branch.
            For changes, please review the commit log.
          artifacts: artifacts/*/*.tar.gz 
